### ISSUE TITLE
Errors found when validating media-channel (from layer-0 YANG)

### ISSUE THREAD

**Issue by danielkinguk** [ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-media-channel-yang#11]
I mostly fixed all the errors of the module and now it is almost aligned with current version of layer0-types, layer0-types-ext and ietf-te-topology. Here is a summary:

-  Whenever a grouping of layer0-types was not found, we look for it in the current version. Most of them were just renamed so it was only a matter of finding the right one.
- Some of the old groupings are no longer in the layer0-types. FEC was in layer0-types-ext but term-type, wavelength assignment and flexi-grid-path-bandwidth were eliminated without clear equivalents. 
- Some TE-topology paths were also wrong. In most cases, it was easy to update them but, in some cases, I didn't find an equivalent node in the current TE-topo doc. In these cases, I comment out those sections.
- In layer-0-types, there is an error causing validation problems. In line 523, I think `must '. >= min-slot-width-factor'` should be `must '. >= ../min-slot-width-factor'`. If someone checks that I am right, we can report this to the authors.

 Any help or comment is welcome with the last three points! :)

_Originally posted by @dperdices in https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-media-channel-yang/issues/1#issuecomment-772474262_

**Comment by italobusi** [comment]
Most of these issues should be resolved with the PR#13

The comment in the latest bullet seems correct: see https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-layer0-types/issues/16
