### ISSUE TITLE
All - Review current YANG code before 24 June 

### ISSUE THREAD

**Issue by danielkinguk** [ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-media-channel-yang#26]
Please review the current YANG code and comment before it is merged with the 04 version of the I-D.

**Comment by sergiobelotti** [comment]
the model is using "l0-tunnel-attributes" and in the grouping there fec-type and termination-type.
Both are connected to l0-types-ext issues , issue #16 https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext/issues/16  and issue #14 https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext/issues/14, that is closed but in fact still waiting for a better description of the term-type. 

Is bit-stuffing needed? Any other attributes is expecting ?
