### ISSUE TITLE
Agree and include use case and example in the document.

### ISSUE THREAD

**Issue by danielkinguk** [ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-media-channel-yang#9]
For Victor and Daniel K.

**Comment by danielkinguk** [comment]
See existing flexi-grid documents that may be useful for the sue case discussion, they may be referenced and reused as needed.

**Comment by danielkinguk** [comment]
Oscar to provide use case example.

**Comment by italobusi** [comment]
These are the slides we have discussed today: [media channel scenarios-00.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-media-channel-yang/files/6358426/media.channel.scenarios-00.pptx)

**Comment by italobusi** [comment]
Slides updated during today's discussion: 
[media channel scenarios-01.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-media-channel-yang/files/6434630/media.channel.scenarios-01.pptx)

**Comment by italobusi** [comment]
Slides updated to address comments from Gabriele: 
[media channel scenarios-02.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-media-channel-yang/files/6471179/media.channel.scenarios-02.pptx)

**Comment by italobusi** [comment]
Updated slide 8 from @sergiobelotti : 
[media channel scenarios-04.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-media-channel-yang/files/6516500/media.channel.scenarios-04.pptx)

**Comment by danielkinguk** [comment]
New UC1/2 combination provided in 04 version of the I-D.
